Repository nbcampMasterChapter3Team4/TeamProject, pull requests merged in 2025-04, with the labels that each got.

#13 [Feat] - PayModal UI를 구현합니다
  TeamProject/TeamProject/Global/Extension/UIView+.swift
  TeamProject/TeamProject/Global/Literals/FontLiterals.swift
  TeamProject/TeamProject/Presentation/Common/BaseView.swift
  TeamProject/TeamProject/Presentation/Common/UIComponent/CustomBottomButton.swift
  TeamProject/TeamProject/Presentation/Pay/View/DeleteButton.swift
  TeamProject/TeamProject/Presentation/Pay/View/ShoppingItemView.swift
  TeamProject/TeamProject/Presentation/Pay/ViewController/PayModalViewController.swift
  TeamProject/TeamProject/Presentation/Pay/ViewController/TestPresentViewController.swift
Labels: 🌱 Feat, 🏰 성우

#15 [Feat] 모달띄우기 & 기기와 해당되는 색 이미지 띄우기
  TeamProject/TeamProject.xcodeproj/project.pbxproj
  TeamProject/TeamProject/Data/Data.swift
  TeamProject/TeamProject/Data/Model/IEColor.swift
  TeamProject/TeamProject/Data/Model/IEProduct.swift
  TeamProject/TeamProject/Presentation/DetailModal/ViewController/DetailModalViewController.swift
  TeamProject/TeamProject/Presentation/DetailModal/Views/DetailColorsStackView.swift
  TeamProject/TeamProject/Presentation/DetailModal/Views/DetailImageView.swift
  TeamProject/TeamProject/Presentation/DetailModal/Views/DetailModalView.swift
  TeamProject/TeamProject/Presentation/Main/ViewController/ViewController.swift
Labels: 🌱 Feat, 🐻‍❄️ 서영

#20 [Feat] #16 - PayModal 상황별 Alert 구현, 디테일 추가
  TeamProject/TeamProject/Global/Extension/String+.swift
  TeamProject/TeamProject/Global/Extension/UIViewController+.swift
  TeamProject/TeamProject/Global/Literals/FontLiterals.swift
  TeamProject/TeamProject/Presentation/Pay/View/DeleteButton.swift
  TeamProject/TeamProject/Presentation/Pay/View/ShoppingItemView.swift
  TeamProject/TeamProject/Presentation/Pay/ViewController/PayModalViewController.swift
Labels: 🌱 Feat, 🐻 세준

#22 [Fix] - ImageLiterals를 '기기이름_기기색상'을 통해 가져올 수 있도록 수정합니다.
  TeamProject/TeamProject/Global/Literals/ImageLiterals.swift
Labels: 🎈 Fix, 🏰 성우

#28 [Feat] #26 PayModel 아이콘 다크모드 수정
  TeamProject/TeamProject/Presentation/Pay/View/DeleteButton.swift
  TeamProject/TeamProject/Presentation/Pay/View/ShoppingItemEmptyView.swift
  TeamProject/TeamProject/Presentation/Pay/View/ShoppingItemView.swift
  TeamProject/TeamProject/Presentation/Pay/ViewController/PayModalViewController.swift
Labels: 🌱 Feat, 🐻 세준

#30 [Feat] DetailModalView UI 구현 & 코어데이터 연결
  TeamProject/TeamProject/Global/Resource/Assets.xcassets/Ic/add_circle_black_ic.imageset/Contents.json
  TeamProject/TeamProject/Global/Resource/Assets.xcassets/Ic/add_circle_black_ic.imageset/add_circle_white_ic.png
  TeamProject/TeamProject/Global/Resource/Assets.xcassets/Ic/add_circle_black_ic.imageset/add_circle_white_ic@2x.png
  TeamProject/TeamProject/Global/Resource/Assets.xcassets/Ic/add_circle_black_ic.imageset/add_circle_white_ic@3x.png
  TeamProject/TeamProject/Global/Resource/Assets.xcassets/Ic/remove_circle_black_ic.imageset/Contents.json
  TeamProject/TeamProject/Global/Resource/Assets.xcassets/Ic/remove_circle_black_ic.imageset/remove_circle_white_ic.png
  TeamProject/TeamProject/Global/Resource/Assets.xcassets/Ic/remove_circle_black_ic.imageset/remove_circle_white_ic@2x.png
  TeamProject/TeamProject/Global/Resource/Assets.xcassets/Ic/remove_circle_black_ic.imageset/remove_circle_white_ic@3x.png
  TeamProject/TeamProject/Presentation/DetailModal/DetailInfoViewDelegate.swift
  TeamProject/TeamProject/Presentation/DetailModal/ViewController/DetailModalViewController.swift
  TeamProject/TeamProject/Presentation/DetailModal/Views/DetailColorsStackView.swift
  TeamProject/TeamProject/Presentation/DetailModal/Views/DetailImageView.swift
  TeamProject/TeamProject/Presentation/DetailModal/Views/DetailInfoView.swift
  TeamProject/TeamProject/Presentation/DetailModal/Views/DetailModalView.swift
  TeamProject/TeamProject/Presentation/Main/ViewController/ViewController.swift
Labels: 🌱 Feat, 🐻‍❄️ 서영

#31 [Feat] #27 - 장바구니 CoreData 연결 및 메인 ViewController에서 상품 관련 기능 구현
  TeamProject/TeamProject/Data/Model/CoreDataManager.swift
  TeamProject/TeamProject/Data/Model/IECategory.swift
  TeamProject/TeamProject/Presentation/Main/Cell/BestItemCell.swift
  TeamProject/TeamProject/Presentation/Main/Cell/MiniItemCell.swift
  TeamProject/TeamProject/Presentation/Main/View/ProductCollectionPageView.swift
  TeamProject/TeamProject/Presentation/Main/ViewController/ViewController.swift
Labels: 🌱 Feat, 🐶 동환

#33 [Feat] #26 PayModalView CoreData 연동
  TeamProject/TeamProject/Data/Model/CoreDataManager.swift
  TeamProject/TeamProject/Data/Model/ShoppingItemModel.swift
  TeamProject/TeamProject/Global/Extension/Int+.swift
  TeamProject/TeamProject/Presentation/Main/Cell/BestItemCell.swift
  TeamProject/TeamProject/Presentation/Main/Cell/MiniItemCell.swift
  TeamProject/TeamProject/Presentation/Main/ViewController/ViewController.swift
  TeamProject/TeamProject/Presentation/Pay/View/ShoppingItemView.swift
  TeamProject/TeamProject/Presentation/Pay/ViewController/PayModalViewController.swift
  TeamProject/TeamProject/Presentation/Pay/ViewController/TestPresentViewController.swift
Labels: 🌱 Feat, 🐻 세준

#42 [Fix] #41 - 아이폰 SE 대응 및 다크모드 미반영 부분 수정
  .github/pull_request_template.md
  TeamProject/TeamProject/Global/Literals/SizeLiterals.swift
  TeamProject/TeamProject/Presentation/DetailModal/Views/CustomRadioButton.swift
  TeamProject/TeamProject/Presentation/DetailModal/Views/DetailImageView.swift
  TeamProject/TeamProject/Presentation/Main/Cell/BestItemCell.swift
  TeamProject/TeamProject/Presentation/Main/Cell/MiniItemCell.swift
  TeamProject/TeamProject/Presentation/Main/View/ProductCollectionPageView.swift
Labels: 🎈 Fix, 🐶 동환

#45 [Feat] #44 - 결제 이스터에그 추가
  TeamProject/TeamProject/Global/Resource/Assets.xcassets/nergullman.imageset/Contents.json
  TeamProject/TeamProject/Global/Resource/Assets.xcassets/nergullman.imageset/Th3Q4XFbaA3FjzgCLPi00gcCAcNsWhKREP2Tz1FKapmDJprA8mkYC6WmbdQD0_JRAD29ibNVm56P0rr5tANCy0N1lHRHhRuObrkBm2ZWH7PGf8ZbmH2mdz0f3YAfGWYS5Q8oPEsV7RZTjjQyf3WLdQ.png
  TeamProject/TeamProject/Presentation/Pay/View/ShoppingItemEmptyView.swift
  TeamProject/TeamProject/Presentation/Pay/ViewController/PayModalViewController.swift
Labels: 🌱 Feat, 🐶 동환
